CREATE TABLE a AS SELECT i FROM generate_series(1,10000) s(i);
ANALYZE a;
EXPLAIN SELECT * FROM a WHERE i*i < -1;

-- EXPLAIN SELECT * FROM a WHERE i*i < 100;
-- EXPLAIN SELECT * FROM a WHERE i BETWEEN -10 AND 10;
