CREATE TABLE a AS SELECT i FROM generate_series(1,1000000) s(i);
ANALYZE a;

EXPLAIN ANALYZE
WITH b AS (SELECT * FROM a WHERE i >= 100)
SELECT * FROM b WHERE i <= 110
  UNION ALL
SELECT * FROM b WHERE i <= 120;
