CREATE TABLE a AS SELECT i FROM generate_series(1,1000000) s(i);
ANALYZE a;

EXPLAIN ANALYZE SELECT * FROM a ORDER BY i;

CREATE INDEX a_idx ON a(i);
ANALYZE a;

EXPLAIN ANALYZE SELECT * FROM a ORDER BY i;
