CREATE TABLE a AS SELECT i FROM generate_series(1,10000) s(i);
CREATE TABLE b AS SELECT i FROM generate_series(1,10000) s(i);
ANALYZE a;
ANALYZE b;

EXPLAIN SELECT * FROM a, b;

CREATE INDEX b_idx ON b(i);
ANALYZE b;

EXPLAIN SELECT * FROM a JOIN b USING (i) WHERE a.i < 10;
EXPLAIN ANALYZE SELECT * FROM a JOIN b USING (i) WHERE a.i < 10;
