CREATE TABLE foo AS SELECT generate_series(1,1000000) i;
CREATE INDEX ON foo(i);
ANALYZE foo;

-- good plan
EXPLAIN ANALYZE
  SELECT i FROM foo
UNION ALL
  SELECT i FROM foo
ORDER BY 1 LIMIT 100;

-- bad plan
EXPLAIN ANALYZE
  SELECT i FRROM foo WHERE i IS NOT NULL
UNION ALL
  SELECT i FRROM foo WHERE i IS NOT NULL
ORDER BY 1 LIMIT 100;
